export namespace Flag {
  export const TRANGQUYNHCODE_AUTO_SHARE = truthy("TRANGQUYNHCODE_AUTO_SHARE")
  export const TRANGQUYNHCODE_GIT_BASH_PATH = process.env["TRANGQUYNHCODE_GIT_BASH_PATH"]
  export const TRANGQUYNHCODE_CONFIG = process.env["TRANGQUYNHCODE_CONFIG"]
  export const TRANGQUYNHCODE_CONFIG_DIR = process.env["TRANGQUYNHCODE_CONFIG_DIR"]
  export const TRANGQUYNHCODE_CONFIG_CONTENT = process.env["TRANGQUYNHCODE_CONFIG_CONTENT"]
  export const TRANGQUYNHCODE_DISABLE_AUTOUPDATE = truthy("TRANGQUYNHCODE_DISABLE_AUTOUPDATE")
  export const TRANGQUYNHCODE_DISABLE_PRUNE = truthy("TRANGQUYNHCODE_DISABLE_PRUNE")
  export const TRANGQUYNHCODE_DISABLE_TERMINAL_TITLE = truthy("TRANGQUYNHCODE_DISABLE_TERMINAL_TITLE")
  export const TRANGQUYNHCODE_PERMISSION = process.env["TRANGQUYNHCODE_PERMISSION"]
  export const TRANGQUYNHCODE_DISABLE_DEFAULT_PLUGINS = truthy("TRANGQUYNHCODE_DISABLE_DEFAULT_PLUGINS")
  export const TRANGQUYNHCODE_DISABLE_LSP_DOWNLOAD = truthy("TRANGQUYNHCODE_DISABLE_LSP_DOWNLOAD")
  export const TRANGQUYNHCODE_ENABLE_EXPERIMENTAL_MODELS = truthy("TRANGQUYNHCODE_ENABLE_EXPERIMENTAL_MODELS")
  export const TRANGQUYNHCODE_DISABLE_AUTOCOMPACT = truthy("TRANGQUYNHCODE_DISABLE_AUTOCOMPACT")
  export const TRANGQUYNHCODE_DISABLE_MODELS_FETCH = truthy("TRANGQUYNHCODE_DISABLE_MODELS_FETCH")
  export const TRANGQUYNHCODE_DISABLE_CLAUDE_CODE = truthy("TRANGQUYNHCODE_DISABLE_CLAUDE_CODE")
  export const TRANGQUYNHCODE_DISABLE_CLAUDE_CODE_PROMPT =
    TRANGQUYNHCODE_DISABLE_CLAUDE_CODE || truthy("TRANGQUYNHCODE_DISABLE_CLAUDE_CODE_PROMPT")
  export const TRANGQUYNHCODE_DISABLE_CLAUDE_CODE_SKILLS =
    TRANGQUYNHCODE_DISABLE_CLAUDE_CODE || truthy("TRANGQUYNHCODE_DISABLE_CLAUDE_CODE_SKILLS")
  export const TRANGQUYNHCODE_FAKE_VCS = process.env["TRANGQUYNHCODE_FAKE_VCS"]
  export const TRANGQUYNHCODE_CLIENT = process.env["TRANGQUYNHCODE_CLIENT"] ?? "cli"
  export const TRANGQUYNHCODE_SERVER_PASSWORD = process.env["TRANGQUYNHCODE_SERVER_PASSWORD"]
  export const TRANGQUYNHCODE_SERVER_USERNAME = process.env["TRANGQUYNHCODE_SERVER_USERNAME"]

  // Experimental
  export const TRANGQUYNHCODE_EXPERIMENTAL = truthy("TRANGQUYNHCODE_EXPERIMENTAL")
  export const TRANGQUYNHCODE_EXPERIMENTAL_FILEWATCHER = truthy("TRANGQUYNHCODE_EXPERIMENTAL_FILEWATCHER")
  export const TRANGQUYNHCODE_EXPERIMENTAL_DISABLE_FILEWATCHER = truthy("TRANGQUYNHCODE_EXPERIMENTAL_DISABLE_FILEWATCHER")
  export const TRANGQUYNHCODE_EXPERIMENTAL_ICON_DISCOVERY =
    TRANGQUYNHCODE_EXPERIMENTAL || truthy("TRANGQUYNHCODE_EXPERIMENTAL_ICON_DISCOVERY")
  export const TRANGQUYNHCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT = truthy("TRANGQUYNHCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")
  export const TRANGQUYNHCODE_ENABLE_EXA =
    truthy("TRANGQUYNHCODE_ENABLE_EXA") || TRANGQUYNHCODE_EXPERIMENTAL || truthy("TRANGQUYNHCODE_EXPERIMENTAL_EXA")
  export const TRANGQUYNHCODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH = number("TRANGQUYNHCODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH")
  export const TRANGQUYNHCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = number("TRANGQUYNHCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS")
  export const TRANGQUYNHCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX = number("TRANGQUYNHCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX")
  export const TRANGQUYNHCODE_EXPERIMENTAL_OXFMT = TRANGQUYNHCODE_EXPERIMENTAL || truthy("TRANGQUYNHCODE_EXPERIMENTAL_OXFMT")
  export const TRANGQUYNHCODE_EXPERIMENTAL_LSP_TY = truthy("TRANGQUYNHCODE_EXPERIMENTAL_LSP_TY")
  export const TRANGQUYNHCODE_EXPERIMENTAL_LSP_TOOL = TRANGQUYNHCODE_EXPERIMENTAL || truthy("TRANGQUYNHCODE_EXPERIMENTAL_LSP_TOOL")
  export const TRANGQUYNHCODE_EXPERIMENTAL_PLAN_MODE = TRANGQUYNHCODE_EXPERIMENTAL || truthy("TRANGQUYNHCODE_EXPERIMENTAL_PLAN_MODE")

  function truthy(key: string) {
    const value = process.env[key]?.toLowerCase()
    return value === "true" || value === "1"
  }

  function number(key: string) {
    const value = process.env[key]
    if (!value) return undefined
    const parsed = Number(value)
    return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
  }
}
